//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É obrigatório informar o CNPJ.
        /// </summary>
        public static string EmpresaCnpjObrigatorio {
            get {
                return ResourceManager.GetString("EmpresaCnpjObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A empresa solicitada não foi encontrada..
        /// </summary>
        public static string EmpresaNaoEncontradaTexto {
            get {
                return ResourceManager.GetString("EmpresaNaoEncontradaTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa não encontrada.
        /// </summary>
        public static string EmpresaNaoEncontradaTitulo {
            get {
                return ResourceManager.GetString("EmpresaNaoEncontradaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É obrigatório informar o nome.
        /// </summary>
        public static string EmpresaNomeObrigatorio {
            get {
                return ResourceManager.GetString("EmpresaNomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É obrigatório informar a unidade federativa.
        /// </summary>
        public static string EmpresaUFObrigatorio {
            get {
                return ResourceManager.GetString("EmpresaUFObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível excluir o identificador {0}..
        /// </summary>
        public static string ErroAoExcluirTexto {
            get {
                return ResourceManager.GetString("ErroAoExcluirTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro excluir registro..
        /// </summary>
        public static string ErroAoExcluirTitulo {
            get {
                return ResourceManager.GetString("ErroAoExcluirTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É obrigatório informar um CPF/CNPJ válido..
        /// </summary>
        public static string FornecedorCPFCNPJInvalido {
            get {
                return ResourceManager.GetString("FornecedorCPFCNPJInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É obrigatório informar o identificador da empresa para o fornecedor..
        /// </summary>
        public static string FornecedorInformarEmpresaID {
            get {
                return ResourceManager.GetString("FornecedorInformarEmpresaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No estado do Paraná, para fornecedores PF é necessário ter no mínimo 18 anos..
        /// </summary>
        public static string FornecedorMenorIdadePRTexto {
            get {
                return ResourceManager.GetString("FornecedorMenorIdadePRTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor menor idade.
        /// </summary>
        public static string FornecedorMenorIdadePRTitulo {
            get {
                return ResourceManager.GetString("FornecedorMenorIdadePRTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado o fornecedor com o identificador informado..
        /// </summary>
        public static string FornecedorNaoEncontradoTexto {
            get {
                return ResourceManager.GetString("FornecedorNaoEncontradoTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor não encontrado.
        /// </summary>
        public static string FornecedorNaoEncontraoTitulo {
            get {
                return ResourceManager.GetString("FornecedorNaoEncontraoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É obrigatório informar a data de nascimento e RG para fornecedores PF.
        /// </summary>
        public static string FornecedorPFInformarDataNascRG {
            get {
                return ResourceManager.GetString("FornecedorPFInformarDataNascRG", resourceCulture);
            }
        }
    }
}
